project:
  type: website
  output-dir: _site

website:
  title: "Vancouver Survival"
  navbar:
    left:
      - text: "Tutorial"
        href: tutorial.qmd
      - text: "Reference"
        href: reference/index.qmd

format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: vancouver_survival
  dir: reference
  sections:
    - title: Survival Tools
      desc: Functions to help you survive in Vancouver.
      contents:
        - clothing.calculate_warmth_score
        - clothing.suggest_rain_gear
        - sustenance.recommend_beverage
