name: 01new-workflow-skeleton
on:
  workflow_dispatch:

jobs:
  build-this:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder step (pass)
      run: true

    - name: Another step in feature branch
      run: |
        echo "Hello, new step"
      
